# generated by datamodel-codegen:
#   filename:  teste.json
#   timestamp: 2023-03-07T19:27:09+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Topic(BaseModel):
    topic: Optional[int] 
    prob: Optional[float] 


class Nt5Alpha005Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha005Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha005Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha005Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt5Alpha005Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha005Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha005Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha005Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt5Alpha005Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha005Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha005Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha005Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt5Alpha005Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha005Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha005Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha005Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt5Alpha01Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha01Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha01Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha01Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt5Alpha01Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha01Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha01Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha01Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt5Alpha01Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha01Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha01Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha01Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt5Alpha01Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha01Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha01Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha01Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt5Alpha05Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha05Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha05Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha05Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt5Alpha05Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha05Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha05Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha05Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt5Alpha05Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha05Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha05Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha05Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt5Alpha05Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha05Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha05Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha05Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt5Alpha09Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha09Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha09Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha09Eta0005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt5Alpha09Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha09Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha09Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha09Eta001(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt5Alpha09Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha09Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha09Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha09Eta005(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt5Alpha09Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt10Alpha09Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt20Alpha09Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Nt40Alpha09Eta01(BaseModel):
    number_of_topics: Optional[int] 
    alpha: Optional[float] 
    eta: Optional[float] 
    topics: Optional[List[Topic]] 


class Topics(BaseModel):
    nt5_alpha0_05_eta0_005: Optional[Nt5Alpha005Eta0005] = Field(
        ..., alias='nt5_alpha0,05_eta0,005'
    )
    nt10_alpha0_05_eta0_005: Optional[Nt10Alpha005Eta0005] = Field(
        ..., alias='nt10_alpha0,05_eta0,005'
    )
    nt20_alpha0_05_eta0_005: Optional[Nt20Alpha005Eta0005] = Field(
        ..., alias='nt20_alpha0,05_eta0,005'
    )
    nt40_alpha0_05_eta0_005: Optional[Nt40Alpha005Eta0005] = Field(
        ..., alias='nt40_alpha0,05_eta0,005'
    )
    nt5_alpha0_05_eta0_01: Optional[Nt5Alpha005Eta001] = Field(
        ..., alias='nt5_alpha0,05_eta0,01'
    )
    nt10_alpha0_05_eta0_01: Optional[Nt10Alpha005Eta001] = Field(
        ..., alias='nt10_alpha0,05_eta0,01'
    )
    nt20_alpha0_05_eta0_01: Optional[Nt20Alpha005Eta001] = Field(
        ..., alias='nt20_alpha0,05_eta0,01'
    )
    nt40_alpha0_05_eta0_01: Optional[Nt40Alpha005Eta001] = Field(
        ..., alias='nt40_alpha0,05_eta0,01'
    )
    nt5_alpha0_05_eta0_05: Optional[Nt5Alpha005Eta005] = Field(
        ..., alias='nt5_alpha0,05_eta0,05'
    )
    nt10_alpha0_05_eta0_05: Optional[Nt10Alpha005Eta005] = Field(
        ..., alias='nt10_alpha0,05_eta0,05'
    )
    nt20_alpha0_05_eta0_05: Optional[Nt20Alpha005Eta005] = Field(
        ..., alias='nt20_alpha0,05_eta0,05'
    )
    nt40_alpha0_05_eta0_05: Optional[Nt40Alpha005Eta005] = Field(
        ..., alias='nt40_alpha0,05_eta0,05'
    )
    nt5_alpha0_05_eta0_1: Optional[Nt5Alpha005Eta01] = Field(
        ..., alias='nt5_alpha0,05_eta0,1'
    )
    nt10_alpha0_05_eta0_1: Optional[Nt10Alpha005Eta01] = Field(
        ..., alias='nt10_alpha0,05_eta0,1'
    )
    nt20_alpha0_05_eta0_1: Optional[Nt20Alpha005Eta01] = Field(
        ..., alias='nt20_alpha0,05_eta0,1'
    )
    nt40_alpha0_05_eta0_1: Optional[Nt40Alpha005Eta01] = Field(
        ..., alias='nt40_alpha0,05_eta0,1'
    )
    nt5_alpha0_1_eta0_005: Optional[Nt5Alpha01Eta0005] = Field(
        ..., alias='nt5_alpha0,1_eta0,005'
    )
    nt10_alpha0_1_eta0_005: Optional[Nt10Alpha01Eta0005] = Field(
        ..., alias='nt10_alpha0,1_eta0,005'
    )
    nt20_alpha0_1_eta0_005: Optional[Nt20Alpha01Eta0005] = Field(
        ..., alias='nt20_alpha0,1_eta0,005'
    )
    nt40_alpha0_1_eta0_005: Optional[Nt40Alpha01Eta0005] = Field(
        ..., alias='nt40_alpha0,1_eta0,005'
    )
    nt5_alpha0_1_eta0_01: Optional[Nt5Alpha01Eta001] = Field(
        ..., alias='nt5_alpha0,1_eta0,01'
    )
    nt10_alpha0_1_eta0_01: Optional[Nt10Alpha01Eta001] = Field(
        ..., alias='nt10_alpha0,1_eta0,01'
    )
    nt20_alpha0_1_eta0_01: Optional[Nt20Alpha01Eta001] = Field(
        ..., alias='nt20_alpha0,1_eta0,01'
    )
    nt40_alpha0_1_eta0_01: Optional[Nt40Alpha01Eta001] = Field(
        ..., alias='nt40_alpha0,1_eta0,01'
    )
    nt5_alpha0_1_eta0_05: Optional[Nt5Alpha01Eta005] = Field(
        ..., alias='nt5_alpha0,1_eta0,05'
    )
    nt10_alpha0_1_eta0_05: Optional[Nt10Alpha01Eta005] = Field(
        ..., alias='nt10_alpha0,1_eta0,05'
    )
    nt20_alpha0_1_eta0_05: Optional[Nt20Alpha01Eta005] = Field(
        ..., alias='nt20_alpha0,1_eta0,05'
    )
    nt40_alpha0_1_eta0_05: Optional[Nt40Alpha01Eta005] = Field(
        ..., alias='nt40_alpha0,1_eta0,05'
    )
    nt5_alpha0_1_eta0_1: Optional[Nt5Alpha01Eta01] = Field(
        ..., alias='nt5_alpha0,1_eta0,1'
    )
    nt10_alpha0_1_eta0_1: Optional[Nt10Alpha01Eta01] = Field(
        ..., alias='nt10_alpha0,1_eta0,1'
    )
    nt20_alpha0_1_eta0_1: Optional[Nt20Alpha01Eta01] = Field(
        ..., alias='nt20_alpha0,1_eta0,1'
    )
    nt40_alpha0_1_eta0_1: Optional[Nt40Alpha01Eta01] = Field(
        ..., alias='nt40_alpha0,1_eta0,1'
    )
    nt5_alpha0_5_eta0_005: Optional[Nt5Alpha05Eta0005] = Field(
        ..., alias='nt5_alpha0,5_eta0,005'
    )
    nt10_alpha0_5_eta0_005: Optional[Nt10Alpha05Eta0005] = Field(
        ..., alias='nt10_alpha0,5_eta0,005'
    )
    nt20_alpha0_5_eta0_005: Optional[Nt20Alpha05Eta0005] = Field(
        ..., alias='nt20_alpha0,5_eta0,005'
    )
    nt40_alpha0_5_eta0_005: Optional[Nt40Alpha05Eta0005] = Field(
        ..., alias='nt40_alpha0,5_eta0,005'
    )
    nt5_alpha0_5_eta0_01: Optional[Nt5Alpha05Eta001] = Field(
        ..., alias='nt5_alpha0,5_eta0,01'
    )
    nt10_alpha0_5_eta0_01: Optional[Nt10Alpha05Eta001] = Field(
        ..., alias='nt10_alpha0,5_eta0,01'
    )
    nt20_alpha0_5_eta0_01: Optional[Nt20Alpha05Eta001] = Field(
        ..., alias='nt20_alpha0,5_eta0,01'
    )
    nt40_alpha0_5_eta0_01: Optional[Nt40Alpha05Eta001] = Field(
        ..., alias='nt40_alpha0,5_eta0,01'
    )
    nt5_alpha0_5_eta0_05: Optional[Nt5Alpha05Eta005] = Field(
        ..., alias='nt5_alpha0,5_eta0,05'
    )
    nt10_alpha0_5_eta0_05: Optional[Nt10Alpha05Eta005] = Field(
        ..., alias='nt10_alpha0,5_eta0,05'
    )
    nt20_alpha0_5_eta0_05: Optional[Nt20Alpha05Eta005] = Field(
        ..., alias='nt20_alpha0,5_eta0,05'
    )
    nt40_alpha0_5_eta0_05: Optional[Nt40Alpha05Eta005] = Field(
        ..., alias='nt40_alpha0,5_eta0,05'
    )
    nt5_alpha0_5_eta0_1: Optional[Nt5Alpha05Eta01] = Field(
        ..., alias='nt5_alpha0,5_eta0,1'
    )
    nt10_alpha0_5_eta0_1: Optional[Nt10Alpha05Eta01] = Field(
        ..., alias='nt10_alpha0,5_eta0,1'
    )
    nt20_alpha0_5_eta0_1: Optional[Nt20Alpha05Eta01] = Field(
        ..., alias='nt20_alpha0,5_eta0,1'
    )
    nt40_alpha0_5_eta0_1: Optional[Nt40Alpha05Eta01] = Field(
        ..., alias='nt40_alpha0,5_eta0,1'
    )
    nt5_alpha0_9_eta0_005: Optional[Nt5Alpha09Eta0005] = Field(
        ..., alias='nt5_alpha0,9_eta0,005'
    )
    nt10_alpha0_9_eta0_005: Optional[Nt10Alpha09Eta0005] = Field(
        ..., alias='nt10_alpha0,9_eta0,005'
    )
    nt20_alpha0_9_eta0_005: Optional[Nt20Alpha09Eta0005] = Field(
        ..., alias='nt20_alpha0,9_eta0,005'
    )
    nt40_alpha0_9_eta0_005: Optional[Nt40Alpha09Eta0005] = Field(
        ..., alias='nt40_alpha0,9_eta0,005'
    )
    nt5_alpha0_9_eta0_01: Optional[Nt5Alpha09Eta001] = Field(
        ..., alias='nt5_alpha0,9_eta0,01'
    )
    nt10_alpha0_9_eta0_01: Optional[Nt10Alpha09Eta001] = Field(
        ..., alias='nt10_alpha0,9_eta0,01'
    )
    nt20_alpha0_9_eta0_01: Optional[Nt20Alpha09Eta001] = Field(
        ..., alias='nt20_alpha0,9_eta0,01'
    )
    nt40_alpha0_9_eta0_01: Optional[Nt40Alpha09Eta001] = Field(
        ..., alias='nt40_alpha0,9_eta0,01'
    )
    nt5_alpha0_9_eta0_05: Optional[Nt5Alpha09Eta005] = Field(
        ..., alias='nt5_alpha0,9_eta0,05'
    )
    nt10_alpha0_9_eta0_05: Optional[Nt10Alpha09Eta005] = Field(
        ..., alias='nt10_alpha0,9_eta0,05'
    )
    nt20_alpha0_9_eta0_05: Optional[Nt20Alpha09Eta005] = Field(
        ..., alias='nt20_alpha0,9_eta0,05'
    )
    nt40_alpha0_9_eta0_05: Optional[Nt40Alpha09Eta005] = Field(
        ..., alias='nt40_alpha0,9_eta0,05'
    )
    nt5_alpha0_9_eta0_1: Optional[Nt5Alpha09Eta01] = Field(
        ..., alias='nt5_alpha0,9_eta0,1'
    )
    nt10_alpha0_9_eta0_1: Optional[Nt10Alpha09Eta01] = Field(
        ..., alias='nt10_alpha0,9_eta0,1'
    )
    nt20_alpha0_9_eta0_1: Optional[Nt20Alpha09Eta01] = Field(
        ..., alias='nt20_alpha0,9_eta0,1'
    )
    nt40_alpha0_9_eta0_1: Optional[Nt40Alpha09Eta01] = Field(
        ..., alias='nt40_alpha0,9_eta0,1'
    )


class Model(BaseModel):
    field_id: Optional[int] = Field(..., alias='_id')
    txt_id: Optional[int] 
    path: Optional[str] 
    phrase: Optional[str] 
    lenght: Optional[int] 
    section: Optional[str] 
    a_id: Optional[int] 
    match_word: Optional[List[str]] 
    topics: Optional[Topics] 
