# generated by datamodel-codegen:
#   filename:  teste.json
#   timestamp: 2023-03-07T00:36:43+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Topic(BaseModel):
    topic: Optional[int] = None
    prob: Optional[float] = None


class Field5t005a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t005a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t005a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t005a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field5t005a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t005a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t005a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t005a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field5t005a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t005a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t005a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t005a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field5t005a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t005a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t005a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t005a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field5t01a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t01a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t01a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t01a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field5t01a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t01a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t01a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t01a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field5t01a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t01a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t01a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t01a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field5t01a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t01a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t01a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t01a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field5t05a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t05a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t05a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t05a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field5t05a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t05a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t05a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t05a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field5t05a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t05a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t05a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t05a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field5t05a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t05a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t05a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t05a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field5t09a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t09a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t09a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t09a0005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field5t09a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t09a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t09a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t09a001e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field5t09a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t09a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t09a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t09a005e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field5t09a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field10t09a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field20t09a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Field40t09a01e(BaseModel):
    number_of_topics: Optional[int] = None
    alpha: Optional[float] = None
    eta: Optional[float] = None
    topics: Optional[List[Topic]] = None


class Topics(BaseModel):
    field_5t_0_05a_0_005e: Optional[Field5t005a0005e] = Field(
        None, alias='5t_0,05a_0,005e'
    )
    field_10t_0_05a_0_005e: Optional[Field10t005a0005e] = Field(
        None, alias='10t_0,05a_0,005e'
    )
    field_20t_0_05a_0_005e: Optional[Field20t005a0005e] = Field(
        None, alias='20t_0,05a_0,005e'
    )
    field_40t_0_05a_0_005e: Optional[Field40t005a0005e] = Field(
        None, alias='40t_0,05a_0,005e'
    )
    field_5t_0_05a_0_01e: Optional[Field5t005a001e] = Field(
        None, alias='5t_0,05a_0,01e'
    )
    field_10t_0_05a_0_01e: Optional[Field10t005a001e] = Field(
        None, alias='10t_0,05a_0,01e'
    )
    field_20t_0_05a_0_01e: Optional[Field20t005a001e] = Field(
        None, alias='20t_0,05a_0,01e'
    )
    field_40t_0_05a_0_01e: Optional[Field40t005a001e] = Field(
        None, alias='40t_0,05a_0,01e'
    )
    field_5t_0_05a_0_05e: Optional[Field5t005a005e] = Field(
        None, alias='5t_0,05a_0,05e'
    )
    field_10t_0_05a_0_05e: Optional[Field10t005a005e] = Field(
        None, alias='10t_0,05a_0,05e'
    )
    field_20t_0_05a_0_05e: Optional[Field20t005a005e] = Field(
        None, alias='20t_0,05a_0,05e'
    )
    field_40t_0_05a_0_05e: Optional[Field40t005a005e] = Field(
        None, alias='40t_0,05a_0,05e'
    )
    field_5t_0_05a_0_1e: Optional[Field5t005a01e] = Field(None, alias='5t_0,05a_0,1e')
    field_10t_0_05a_0_1e: Optional[Field10t005a01e] = Field(
        None, alias='10t_0,05a_0,1e'
    )
    field_20t_0_05a_0_1e: Optional[Field20t005a01e] = Field(
        None, alias='20t_0,05a_0,1e'
    )
    field_40t_0_05a_0_1e: Optional[Field40t005a01e] = Field(
        None, alias='40t_0,05a_0,1e'
    )
    field_5t_0_1a_0_005e: Optional[Field5t01a0005e] = Field(
        None, alias='5t_0,1a_0,005e'
    )
    field_10t_0_1a_0_005e: Optional[Field10t01a0005e] = Field(
        None, alias='10t_0,1a_0,005e'
    )
    field_20t_0_1a_0_005e: Optional[Field20t01a0005e] = Field(
        None, alias='20t_0,1a_0,005e'
    )
    field_40t_0_1a_0_005e: Optional[Field40t01a0005e] = Field(
        None, alias='40t_0,1a_0,005e'
    )
    field_5t_0_1a_0_01e: Optional[Field5t01a001e] = Field(None, alias='5t_0,1a_0,01e')
    field_10t_0_1a_0_01e: Optional[Field10t01a001e] = Field(
        None, alias='10t_0,1a_0,01e'
    )
    field_20t_0_1a_0_01e: Optional[Field20t01a001e] = Field(
        None, alias='20t_0,1a_0,01e'
    )
    field_40t_0_1a_0_01e: Optional[Field40t01a001e] = Field(
        None, alias='40t_0,1a_0,01e'
    )
    field_5t_0_1a_0_05e: Optional[Field5t01a005e] = Field(None, alias='5t_0,1a_0,05e')
    field_10t_0_1a_0_05e: Optional[Field10t01a005e] = Field(
        None, alias='10t_0,1a_0,05e'
    )
    field_20t_0_1a_0_05e: Optional[Field20t01a005e] = Field(
        None, alias='20t_0,1a_0,05e'
    )
    field_40t_0_1a_0_05e: Optional[Field40t01a005e] = Field(
        None, alias='40t_0,1a_0,05e'
    )
    field_5t_0_1a_0_1e: Optional[Field5t01a01e] = Field(None, alias='5t_0,1a_0,1e')
    field_10t_0_1a_0_1e: Optional[Field10t01a01e] = Field(None, alias='10t_0,1a_0,1e')
    field_20t_0_1a_0_1e: Optional[Field20t01a01e] = Field(None, alias='20t_0,1a_0,1e')
    field_40t_0_1a_0_1e: Optional[Field40t01a01e] = Field(None, alias='40t_0,1a_0,1e')
    field_5t_0_5a_0_005e: Optional[Field5t05a0005e] = Field(
        None, alias='5t_0,5a_0,005e'
    )
    field_10t_0_5a_0_005e: Optional[Field10t05a0005e] = Field(
        None, alias='10t_0,5a_0,005e'
    )
    field_20t_0_5a_0_005e: Optional[Field20t05a0005e] = Field(
        None, alias='20t_0,5a_0,005e'
    )
    field_40t_0_5a_0_005e: Optional[Field40t05a0005e] = Field(
        None, alias='40t_0,5a_0,005e'
    )
    field_5t_0_5a_0_01e: Optional[Field5t05a001e] = Field(None, alias='5t_0,5a_0,01e')
    field_10t_0_5a_0_01e: Optional[Field10t05a001e] = Field(
        None, alias='10t_0,5a_0,01e'
    )
    field_20t_0_5a_0_01e: Optional[Field20t05a001e] = Field(
        None, alias='20t_0,5a_0,01e'
    )
    field_40t_0_5a_0_01e: Optional[Field40t05a001e] = Field(
        None, alias='40t_0,5a_0,01e'
    )
    field_5t_0_5a_0_05e: Optional[Field5t05a005e] = Field(None, alias='5t_0,5a_0,05e')
    field_10t_0_5a_0_05e: Optional[Field10t05a005e] = Field(
        None, alias='10t_0,5a_0,05e'
    )
    field_20t_0_5a_0_05e: Optional[Field20t05a005e] = Field(
        None, alias='20t_0,5a_0,05e'
    )
    field_40t_0_5a_0_05e: Optional[Field40t05a005e] = Field(
        None, alias='40t_0,5a_0,05e'
    )
    field_5t_0_5a_0_1e: Optional[Field5t05a01e] = Field(None, alias='5t_0,5a_0,1e')
    field_10t_0_5a_0_1e: Optional[Field10t05a01e] = Field(None, alias='10t_0,5a_0,1e')
    field_20t_0_5a_0_1e: Optional[Field20t05a01e] = Field(None, alias='20t_0,5a_0,1e')
    field_40t_0_5a_0_1e: Optional[Field40t05a01e] = Field(None, alias='40t_0,5a_0,1e')
    field_5t_0_9a_0_005e: Optional[Field5t09a0005e] = Field(
        None, alias='5t_0,9a_0,005e'
    )
    field_10t_0_9a_0_005e: Optional[Field10t09a0005e] = Field(
        None, alias='10t_0,9a_0,005e'
    )
    field_20t_0_9a_0_005e: Optional[Field20t09a0005e] = Field(
        None, alias='20t_0,9a_0,005e'
    )
    field_40t_0_9a_0_005e: Optional[Field40t09a0005e] = Field(
        None, alias='40t_0,9a_0,005e'
    )
    field_5t_0_9a_0_01e: Optional[Field5t09a001e] = Field(None, alias='5t_0,9a_0,01e')
    field_10t_0_9a_0_01e: Optional[Field10t09a001e] = Field(
        None, alias='10t_0,9a_0,01e'
    )
    field_20t_0_9a_0_01e: Optional[Field20t09a001e] = Field(
        None, alias='20t_0,9a_0,01e'
    )
    field_40t_0_9a_0_01e: Optional[Field40t09a001e] = Field(
        None, alias='40t_0,9a_0,01e'
    )
    field_5t_0_9a_0_05e: Optional[Field5t09a005e] = Field(None, alias='5t_0,9a_0,05e')
    field_10t_0_9a_0_05e: Optional[Field10t09a005e] = Field(
        None, alias='10t_0,9a_0,05e'
    )
    field_20t_0_9a_0_05e: Optional[Field20t09a005e] = Field(
        None, alias='20t_0,9a_0,05e'
    )
    field_40t_0_9a_0_05e: Optional[Field40t09a005e] = Field(
        None, alias='40t_0,9a_0,05e'
    )
    field_5t_0_9a_0_1e: Optional[Field5t09a01e] = Field(None, alias='5t_0,9a_0,1e')
    field_10t_0_9a_0_1e: Optional[Field10t09a01e] = Field(None, alias='10t_0,9a_0,1e')
    field_20t_0_9a_0_1e: Optional[Field20t09a01e] = Field(None, alias='20t_0,9a_0,1e')
    field_40t_0_9a_0_1e: Optional[Field40t09a01e] = Field(None, alias='40t_0,9a_0,1e')


class Model(BaseModel):
    field_id: Optional[int] = Field(None, alias='_id')
    txt_id: Optional[int] = None
    path: Optional[str] = None
    phrase: Optional[str] = None
    lenght: Optional[int] = None
    section: Optional[str] = None
    a_id: Optional[int] = None
    match_word: Optional[List[str]] = None
    topics: Optional[Topics] = None
