# generated by datamodel-codegen:
#   filename:  teste.json
#   timestamp: 2023-03-07T00:23:04+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class Topic(BaseModel):
    topic: int
    prob: float


class Field5t005a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t005a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t005a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t005a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field5t005a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t005a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t005a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t005a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field5t005a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t005a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t005a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t005a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field5t005a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t005a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t005a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t005a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field5t01a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t01a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t01a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t01a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field5t01a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t01a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t01a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t01a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field5t01a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t01a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t01a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t01a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field5t01a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t01a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t01a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t01a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field5t05a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t05a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t05a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t05a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field5t05a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t05a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t05a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t05a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field5t05a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t05a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t05a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t05a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field5t05a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t05a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t05a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t05a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field5t09a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t09a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t09a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t09a0005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field5t09a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t09a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t09a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t09a001e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field5t09a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t09a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t09a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t09a005e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field5t09a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field10t09a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field20t09a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Field40t09a01e(BaseModel):
    number_of_topics: int
    alpha: float
    eta: float
    topics: List[Topic]


class Topics(BaseModel):
    field_5t_0_05a_0_005e: Field5t005a0005e = Field(..., alias='5t_0,05a_0,005e')
    field_10t_0_05a_0_005e: Field10t005a0005e = Field(..., alias='10t_0,05a_0,005e')
    field_20t_0_05a_0_005e: Field20t005a0005e = Field(..., alias='20t_0,05a_0,005e')
    field_40t_0_05a_0_005e: Field40t005a0005e = Field(..., alias='40t_0,05a_0,005e')
    field_5t_0_05a_0_01e: Field5t005a001e = Field(..., alias='5t_0,05a_0,01e')
    field_10t_0_05a_0_01e: Field10t005a001e = Field(..., alias='10t_0,05a_0,01e')
    field_20t_0_05a_0_01e: Field20t005a001e = Field(..., alias='20t_0,05a_0,01e')
    field_40t_0_05a_0_01e: Field40t005a001e = Field(..., alias='40t_0,05a_0,01e')
    field_5t_0_05a_0_05e: Field5t005a005e = Field(..., alias='5t_0,05a_0,05e')
    field_10t_0_05a_0_05e: Field10t005a005e = Field(..., alias='10t_0,05a_0,05e')
    field_20t_0_05a_0_05e: Field20t005a005e = Field(..., alias='20t_0,05a_0,05e')
    field_40t_0_05a_0_05e: Field40t005a005e = Field(..., alias='40t_0,05a_0,05e')
    field_5t_0_05a_0_1e: Field5t005a01e = Field(..., alias='5t_0,05a_0,1e')
    field_10t_0_05a_0_1e: Field10t005a01e = Field(..., alias='10t_0,05a_0,1e')
    field_20t_0_05a_0_1e: Field20t005a01e = Field(..., alias='20t_0,05a_0,1e')
    field_40t_0_05a_0_1e: Field40t005a01e = Field(..., alias='40t_0,05a_0,1e')
    field_5t_0_1a_0_005e: Field5t01a0005e = Field(..., alias='5t_0,1a_0,005e')
    field_10t_0_1a_0_005e: Field10t01a0005e = Field(..., alias='10t_0,1a_0,005e')
    field_20t_0_1a_0_005e: Field20t01a0005e = Field(..., alias='20t_0,1a_0,005e')
    field_40t_0_1a_0_005e: Field40t01a0005e = Field(..., alias='40t_0,1a_0,005e')
    field_5t_0_1a_0_01e: Field5t01a001e = Field(..., alias='5t_0,1a_0,01e')
    field_10t_0_1a_0_01e: Field10t01a001e = Field(..., alias='10t_0,1a_0,01e')
    field_20t_0_1a_0_01e: Field20t01a001e = Field(..., alias='20t_0,1a_0,01e')
    field_40t_0_1a_0_01e: Field40t01a001e = Field(..., alias='40t_0,1a_0,01e')
    field_5t_0_1a_0_05e: Field5t01a005e = Field(..., alias='5t_0,1a_0,05e')
    field_10t_0_1a_0_05e: Field10t01a005e = Field(..., alias='10t_0,1a_0,05e')
    field_20t_0_1a_0_05e: Field20t01a005e = Field(..., alias='20t_0,1a_0,05e')
    field_40t_0_1a_0_05e: Field40t01a005e = Field(..., alias='40t_0,1a_0,05e')
    field_5t_0_1a_0_1e: Field5t01a01e = Field(..., alias='5t_0,1a_0,1e')
    field_10t_0_1a_0_1e: Field10t01a01e = Field(..., alias='10t_0,1a_0,1e')
    field_20t_0_1a_0_1e: Field20t01a01e = Field(..., alias='20t_0,1a_0,1e')
    field_40t_0_1a_0_1e: Field40t01a01e = Field(..., alias='40t_0,1a_0,1e')
    field_5t_0_5a_0_005e: Field5t05a0005e = Field(..., alias='5t_0,5a_0,005e')
    field_10t_0_5a_0_005e: Field10t05a0005e = Field(..., alias='10t_0,5a_0,005e')
    field_20t_0_5a_0_005e: Field20t05a0005e = Field(..., alias='20t_0,5a_0,005e')
    field_40t_0_5a_0_005e: Field40t05a0005e = Field(..., alias='40t_0,5a_0,005e')
    field_5t_0_5a_0_01e: Field5t05a001e = Field(..., alias='5t_0,5a_0,01e')
    field_10t_0_5a_0_01e: Field10t05a001e = Field(..., alias='10t_0,5a_0,01e')
    field_20t_0_5a_0_01e: Field20t05a001e = Field(..., alias='20t_0,5a_0,01e')
    field_40t_0_5a_0_01e: Field40t05a001e = Field(..., alias='40t_0,5a_0,01e')
    field_5t_0_5a_0_05e: Field5t05a005e = Field(..., alias='5t_0,5a_0,05e')
    field_10t_0_5a_0_05e: Field10t05a005e = Field(..., alias='10t_0,5a_0,05e')
    field_20t_0_5a_0_05e: Field20t05a005e = Field(..., alias='20t_0,5a_0,05e')
    field_40t_0_5a_0_05e: Field40t05a005e = Field(..., alias='40t_0,5a_0,05e')
    field_5t_0_5a_0_1e: Field5t05a01e = Field(..., alias='5t_0,5a_0,1e')
    field_10t_0_5a_0_1e: Field10t05a01e = Field(..., alias='10t_0,5a_0,1e')
    field_20t_0_5a_0_1e: Field20t05a01e = Field(..., alias='20t_0,5a_0,1e')
    field_40t_0_5a_0_1e: Field40t05a01e = Field(..., alias='40t_0,5a_0,1e')
    field_5t_0_9a_0_005e: Field5t09a0005e = Field(..., alias='5t_0,9a_0,005e')
    field_10t_0_9a_0_005e: Field10t09a0005e = Field(..., alias='10t_0,9a_0,005e')
    field_20t_0_9a_0_005e: Field20t09a0005e = Field(..., alias='20t_0,9a_0,005e')
    field_40t_0_9a_0_005e: Field40t09a0005e = Field(..., alias='40t_0,9a_0,005e')
    field_5t_0_9a_0_01e: Field5t09a001e = Field(..., alias='5t_0,9a_0,01e')
    field_10t_0_9a_0_01e: Field10t09a001e = Field(..., alias='10t_0,9a_0,01e')
    field_20t_0_9a_0_01e: Field20t09a001e = Field(..., alias='20t_0,9a_0,01e')
    field_40t_0_9a_0_01e: Field40t09a001e = Field(..., alias='40t_0,9a_0,01e')
    field_5t_0_9a_0_05e: Field5t09a005e = Field(..., alias='5t_0,9a_0,05e')
    field_10t_0_9a_0_05e: Field10t09a005e = Field(..., alias='10t_0,9a_0,05e')
    field_20t_0_9a_0_05e: Field20t09a005e = Field(..., alias='20t_0,9a_0,05e')
    field_40t_0_9a_0_05e: Field40t09a005e = Field(..., alias='40t_0,9a_0,05e')
    field_5t_0_9a_0_1e: Field5t09a01e = Field(..., alias='5t_0,9a_0,1e')
    field_10t_0_9a_0_1e: Field10t09a01e = Field(..., alias='10t_0,9a_0,1e')
    field_20t_0_9a_0_1e: Field20t09a01e = Field(..., alias='20t_0,9a_0,1e')
    field_40t_0_9a_0_1e: Field40t09a01e = Field(..., alias='40t_0,9a_0,1e')


class Model(BaseModel):
    field_id: int = Field(..., alias='_id')
    txt_id: int
    path: str
    phrase: str
    lenght: int
    section: str
    a_id: int
    match_word: List[str]
    topics: Topics
